[build]
  functions = "./netlify/functions" # The directory where your serverless functions are located
  publish = "build" # The directory where your front-end code is located (if applicable)
  command = "npm run build" # The build command to run your front-end build process (if applicable)
